{{/*
This file defines following resource objects: 
- a Service ClusterIP for movie application
- a Service ClusterIP for cast application
- a Service NodePort to public nginx reverse proxy from outside cluster
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie-service
  labels:
    app: {{ .Release.Name }}-movie-service
spec:
  type: {{ .Values.movieService.service.type }}
  ports:
    - name: http
      port: {{ .Values.movieService.service.port }}
      targetPort: http
      protocol: TCP   
  selector:
    app: {{ .Release.Name }}-movie-service

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast-service
  labels:
    app: {{ .Release.Name }}-cast-service
spec:
  type: {{ .Values.castService.service.type }}
  ports:
    - name: http
      port: {{ .Values.castService.service.port }}
      targetPort: http
      protocol: TCP   
  selector:
    app: {{ .Release.Name }}-cast-service

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      protocol: TCP   
  selector:
    app: {{ .Release.Name }}-nginx