{{/*
This file defines following resource objects: 
- a StatefulSet, a PVC for movieDB container
- a StatefulSet, a PVC for castDB container
*/}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-movie-db
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie-db
    spec:
      containers:
      - name: movie-db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        ports:
        - containerPort: {{ .Values.movieDB.service.port }}
        volumeMounts:
        - name: {{ .Values.volume.name }}-movie
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        env:
        - name: POSTGRES_USER
          value: "movie_db_username"
        - name: POSTGRES_PASSWORD
          value: "movie_db_password"
        - name: POSTGRES_DB
          value: "movie_db_dev"
      volumes:
      - name: {{ .Values.volume.name }}-movie
        persistentVolumeClaim:
          claimName: {{ .Values.volume.name }}-movie

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.name }}-movie
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  storageClassName: {{ .Values.volume.storageClassName}}
  resources:
    requests:
      storage: {{ .Values.volume.storage}}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-cast-db
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cast-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cast-db
    spec:
      containers:
      - name: cast-db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        ports:
        - containerPort: {{ .Values.castDB.service.port }}
        volumeMounts:
        - name: {{ .Values.volume.name }}-cast
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        env:
        - name: POSTGRES_DB
          value: {{ .Values.castDB.name }}
        - name: POSTGRES_USER
          value: {{ .Values.castDB.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.castDB.pw }}
      volumes:
      - name: {{ .Values.volume.name }}-cast
        persistentVolumeClaim:
          claimName: {{ .Values.volume.name }}-cast

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.name }}-cast
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  storageClassName: {{ .Values.volume.storageClassName}}
  resources:
    requests:
      storage: {{ .Values.volume.storage}}
